### ISSUE TITLE
Compilation fails on Debian testing

### ISSUE THREAD

**Issue by craigbarnes** [wahern/cqueues#113]
Using `make cqueues5.3` on a Debian Stretch system with OpenSSL 1.0.2 fails with the following error:

```
~/cqueues/src/lib/socket.c: In function ‘so_starttls’:
~/cqueues/src/lib/socket.c:2089:53: warning: implicit declaration of function ‘SSLv3_server_method’ [-Wimplicit-function-declaration]
  if (!method->ssl_connect || method->ssl_connect == SSLv3_server_method()->ssl_
                                                     ^
~/cqueues/src/lib/socket.c:2089:74: error: invalid type argument of ‘->’ (have ‘int’)
 !method->ssl_connect || method->ssl_connect == SSLv3_server_method()->ssl_conne
                                                                     ^
~/cqueues/src/lib/GNUmakefile:37: recipe for target '~/cqueues/src/lib/socket.o' failed
make: *** [~/cqueues/src/lib/socket.o] Error 1
```

I'm guessing because libssl was built with the `no-ssl3` option.

**Comment by daurnimator** [comment]
Related issue in luasec: https://github.com/brunoos/luasec/issues/58

**Comment by rtsisyk** [comment]
I have the same problem.
Debian stretch/sid
libssl-dev:
  Installed: 1.0.2e-1

Could you please fix this problem in the similar way to luaossl?
I want to create DEB/RPM packages.

**Comment by daurnimator** [comment]
> Could you please fix this problem in the similar way to luaossl?

There is a pull request (#114) waiting for @wahern 's approval.

> I want to create DEB/RPM packages.

FWIW, there is already a 'debian' directory in the cqueues dir, just run `make debian` to build it :)
On the other hand, it doesn't follow the latest debian packaging guidelines (see #19).
