### ISSUE TITLE
Building with multiple include dirs

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#139]
If I have lua at `/foo/lua.h` and openssl at `/bar/openssl/openssl.h` what are the make arguments I should pass?

**Comment by ChickenNuggers** [comment]
Is there a flag that passes extra C compiler options? If so, `-I/foo -I/bar` where neither are `/usr/include` or already searched, etc.

**Comment by daurnimator** [comment]
The makefile has the variable `includedir`, which seems to just be for lua headers? but I'm not sure.

**Comment by wahern** [comment]
The Makefile uses GNU conventions for Makefile variables, which are the only rigorously documented conventions I know of.

All the lowercase variables are [_installation_ paths](http://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables). That is, where to install the application, not where dependencies are installed. The exception is [DESTDIR](http://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR).

All the uppercase variables are for compiling: command paths and command arguments. For preprocessor flags just specify CPPFLAGS with all the include directories needed.

```
$ make CPPFLAGS="-I/foo -I/bar"
```

The GNU convention is that CPPFLAGS is user-specifiable. Required flags set by the build system go into ALL_CPPFLAGS, which appends CPPFLAGS. ALL_CPPFLAGS can also be specified, but then you have to make sure to specify everything manually.

The conventional macros for C builds are:

- CPPFLAGS: Preprocessor flags. E.g. `-I/bar/include -DBAR=1`
- CFLAGS: General compiler flags
- SOFLAGS: Compiler flags specific to creating dynamic libraries. E.g. `-shared`
- LDFLAGS: Linker flags, but _not_ including actual libraries. E.g. `-L/foo/lib -Wl,rpath,/foo/lib`
- LIBS: Libraries to link against E.g. `-lfoo`

In the latest cqueues build I've added some additional macros, LUAxy_CPPFLAGS, so you can specify preprocessor flags unique to each Lua version. Previously luapath was always invoked to locate the API headers. That's still the case now when LUAxy_CPPFLAGS are not explicitly specified. 

The easiest way to make sure that luapath can find the headers is to make sure all your interpreter binaries are reachable via PATH. Then, among other places, luapath will recursively search for headers under /foo/bin/lua/../../include. But you can also specify all of them in CPPFLAGS, and luapath will iteratively search all the `-I` directories for version-specific headers and set LUA51_CPPFLAGS, etc, accordingly. (LUAxy_CPPFLAGS comes before CPPFLAGS in the command rule so it has priority.)

To avoid luapath entirely specify LUA51_CPPFLAGS, LUA52_CPPFLAGS, and/or LUA53_CPPFLAGS. To avoid all automatic configuration specify those plus ALL_CPPFLAGS, ALL_CFLAGS, ALL_SOFLAGS, ALL_LDFLAGS, and ALL_LIBS.
