### ISSUE TITLE
Problems with connecting to IPv6 only address

### ISSUE THREAD

**Issue by torhve** [wahern/cqueues#147]
Trying to connect with

```lua
print(require"cqueues.socket".connect("ipv6.xt.gg", 80):connect())
```

gives result:
```
lua: /usr/local/share/lua/5.1/cqueues/socket.lua:263: socket:connect: The name does not resolve for the supplied parameters
```

`ipv6.xt.gg` only has AAAA record

**Comment by daurnimator** [comment]
replicated locally.

**Comment by wahern** [comment]
I'm working on adding better IPv6 in dns.c right now--specifically, fixing `getaddrinfo`-like API to resolve both IPv4 and IPv6, and then fixing up socket.c to make use of it. I'll try to get it out ASAP.

**Comment by wahern** [comment]
I've committed [upstream] dual-family IPv4/IPv6 support in the addrinfo iterator of the embedded dns.c library. Next step is to merge it downsteam into cqueues and fix how so_open and dns_ai_open are called internally.

**Comment by wahern** [comment]
This works for me in the latest release:

```
RUNLUA_S=regress/.local mk/runlua examples/simple.get "ipv6.xt.gg"
```

Note this is after running `make check`, where the runlua script can locate fresh modules under regress/.local.
