### ISSUE TITLE
Avoid use of ephemeron table

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#149]
Investigating https://github.com/daurnimator/lua-http/issues/32 I was reading through the cqueues code to see how it uses ephemeron tables.

  - each cqueue has an weakly keyed ephemeron table in the registry. This is stored in `Q->registry` by use of `luaL_reg`.
  - inside of this ephemeron table there is a single pair. the key is the cqueue itself; the value is a table
  - in `cqueue_enter` we obtain this table and keep a temporary reference in `I->registry`.
  - This `I->registry` is used via the short functions `cqueue_ref` and `cqueue_unref` to keep references
  - The sole user of `cqueue_ref` and `cqueue_unref` is `thread_add` and `thread_del`. They store a reference to a lua thread's `lua_State*` into `T->L`, it ensures the pointer is valid by using  `cqueue_ref` and saving it in `T->ref`.

## Questions/Solutions

  - Instead of keeping `I->registry` in an ephemeron table, could we store it in a cqueue's `uservalue`.
  - Instead of using `cqueue_ref` in `thread_add`, why not just use `luaL_ref` with `LUA_REGISTRYINDEX`?

**Comment by daurnimator** [comment]
Neither of the solutions mentioned absolve the need for the ephemeron table.

> Instead of keeping `I->registry` in an ephemeron table, could we store it in a cqueue's uservalue.

You *can* replace `Q->registry` via using uservalues; but it doesn't solve the ephemeron table requirement.
In terms of pursuing this anyway, it doesn't really save **that** much: you're swapping a table indexing operation for `lua_getuservalue` for each `cqueue_enter` call.

> Instead of using `cqueue_ref` in thread_add, why not just use `luaL_ref` with `LUA_REGISTRYINDEX`?

This anchors threads until they get manually deleted with `thread_del`. If they hold a reference to their own cq, the cq won't get collected, and hence the thread won't get deleted.

----------------------

What seems to be required is to have the cqueue => thread link visible to the garbage collector.

**Comment by daurnimator** [comment]
> What seems to be required is to have the cqueue => thread link visible to the garbage collector.

I got some progress on a branch over here: https://github.com/daurnimator/cqueues/tree/149-no-ephemeron-table

**Comment by wahern** [comment]
Yes, we should be using the user value feature. Lua 5.1 didn't have user values, and originally I was trying to keep the code as similar as possible across all supported versions.

**Comment by daurnimator** [comment]
5.1 has object environments, which work the same as uservalues

**Comment by wahern** [comment]
lua_setfenv doesn't permit assigning nil, so there's no way to clear the uservalue. Whether that's related or not, I was seeing segaults on some regression tests under Lua 5.1 (for #85 and #59 in particular). One fix is to always use an intermediate table for 5.1. Still investigating....

**Comment by daurnimator** [comment]
> lua_setfenv doesn't permit assigning nil, so there's no way to clear the uservalue

Looking at the lua source I don't see why that would be the case.....

**Comment by daurnimator** [comment]
> Looking at the lua source I don't see why that would be the case.....

Oh, I see this now:
```C
  api_check(L, ttistable(L->top - 1));
```

**Comment by daurnimator** [comment]
Fix merged in d1a696b0da82d3780435249be302ef0cef9421de
