### ISSUE TITLE
cqueues fails to build from source with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by oerdnj** [wahern/cqueues#160]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835785
> Hi,
>
> OpenSSL 1.1.0 is about to released.  During a rebuild of all
> packages using OpenSSL this package fail to build.  A log of that
> build can be found at:
> https://breakpoint.cc/openssl-1.1-rebuild-2016-08-26/failed/lua-cqueues_20160812-1_amd64-2016-08-26T19%3A13%3A17Z
> 
> On https://wiki.openssl.org/index.php/1.1_API_Changes you can see
> various of the reasons why it might fail.  There are also updated
> man pages at https://www.openssl.org/docs/manmaster/ that should
> contain useful information.

**Comment by oerdnj** [comment]
And this is probably the similar problem solved in nginx:
https://forum.nginx.org/read.php?29,265786

**Comment by daurnimator** [comment]
Fixed with 45acf603447a63a2e9aff1681b236e3123610fad via #162
