### ISSUE TITLE
build failure with libressl 2.5.3

### ISSUE THREAD

**Issue by ncopa** [wahern/cqueues#182]
When building with libressl 2.5.3 on alpine linux:

````shell
gcc -O2 -std=gnu99 -fPIC -g -Wall -Wextra  -Wno-missing-field-initializers  -Wno-override-init -Wno-unused -Os -fomit-frame-pointer -DHAVE_EVENTFD=1 -DHAVE_EPOLL_CREATE1=1 -DHAVE_PIPE2=1 -D_REENTRANT -D_THREAD_SAFE -D_GNU_SOURCE -Os -fomit-frame-pointer -DSOCKET_DEBUG -DHAVE_CONFIG_H -DDNS_RANDOM=RAND_bytes -c -o /home/ncopa/aports/main/lua-cqueues/src/cqueues-rel-20161215/src/lib/notify.o /home/ncopa/aports/main/lua-cqueues/src/cqueues-rel-20161215/src/lib/notify.c
/home/ncopa/aports/main/lua-cqueues/src/cqueues-rel-20161215/src/lib/socket.c: In function 'compat_SSL_is_server':
/home/ncopa/aports/main/lua-cqueues/src/cqueues-rel-20161215/src/lib/socket.c:193:13: error: 'SSL_METHOD {aka const struct ssl_method_st}' has no member named 'ssl_connect'
  if (!method->ssl_connect || method->ssl_connect == SSLv23_server_method()->ssl_connect)
             ^~
/home/ncopa/aports/main/lua-cqueues/src/cqueues-rel-20161215/src/lib/socket.c:193:36: error: 'SSL_METHOD {aka const struct ssl_method_st}' has no member named 'ssl_connect'
  if (!method->ssl_connect || method->ssl_connect == SSLv23_server_method()->ssl_connect)
                                    ^~
/home/ncopa/aports/main/lua-cqueues/src/cqueues-rel-20161215/src/lib/socket.c:193:75: error: 'SSL_METHOD {aka const struct ssl_method_st}' has no member named 'ssl_connect'
  if (!method->ssl_connect || method->ssl_connect == SSLv23_server_method()->ssl_connect)
````

**Comment by daurnimator** [comment]
Try compiling with `-DHAVE_SSL_IS_SERVER`.

**Comment by ncopa** [comment]
I sent patch to libressl to implement `SSL_is_server`. This is the response.

> Thanks for the diff, however at this stage we do not currently plan on adding 
> the OpenSSL 1.1 accessors, primarily due to the fact that OpenSSL seemingly 
> has no migration plan from 1.0 to 1.1. This may change at some point, but once 
> we add one or two we're basically committed to providing all of them.
> 
> > ---
> > The reason for the need of this is explained here:
> > https://github.com/wahern/cqueues/issues/182  
> 
> The code referenced seems unnecessarily complex (and potentially error prone) 
> - if the SSL_is_server() call below works, then it can simply use the server 
> member (available in OpenSSL 1.0 and LibreSSL) of the SSL struct without the 
> below wrapper.

**Comment by ncopa** [comment]
This is the workaround we use in Alpine in case someone else should bump into this:
````diff
diff --git a/src/lib/socket.c b/src/lib/socket.c
index 390896f..51ac128 100644
--- a/src/lib/socket.c
+++ b/src/lib/socket.c
@@ -86,6 +86,10 @@ int socket_v_api(void) {
        return SOCKET_V_API;
 } /* socket_v_api() */
 
+#if LIBRESSL_VERSION_NUMBER >= 0x2050100fL
+#define HAVE_SSL_IS_SERVER 1
+#define SSL_is_server(s) (s)->server
+#endif
 
 /*
  * F E A T U R E  R O U T I N E S
````

**Comment by RussellHaley** [comment]
> This is the workaround we use in Alpine in case someone else should bump into this:
Patch allows me to build cqueues on TrueOS (FreeBSD 12-Current, LibreSSL 2.5.4 ). Thanks.

**Comment by RussellHaley** [comment]
This issue prevents me from using cqueues from luarocks. My preference is for LibreSSL so it keeps coming up. I suspect it will be a show stopper on NetBSD as well. I'll check if I can patch in luarocks.

**Comment by benrob0329** [comment]
@RussellHaley Any progress on that? Can't install on Void Linux because of this.
