### ISSUE TITLE
incorrect .VERSION in latest release

### ISSUE THREAD

**Issue by vcunat** [wahern/cqueues#216]
In [latest release](https://github.com/wahern/cqueues/releases/tag/rel-20171014) called "20171014":
```
> require('cqueues').VERSION
20161215
```

I think it's really confusing; hopefully future releases can get this right.

**Comment by vcunat** [comment]
Apparently something is breaking detection in the build system in **my** case and not in general.  Workaround: override during compilation by `-DCQUEUES_VERSION=20171014` in CFLAGS.

**Comment by daurnimator** [comment]
> Apparently something is breaking detection in the build system in **my** case and not in general.

How are you buildling cqueues?

**Comment by vcunat** [comment]
I can't see anything really special; it's basically just running make &ndash; with flags e.g.

`SHELL=/nix/store/yjkch3aia9ny4dq42dbcjrdwqb1y8c33-bash-4.4-p23/bin/bash PREFIX=\$\(out\) LUA_LIBDIR=\$\(out\)/lib/lua/5.1 LUA_INC=-I/nix/store/zrarsvfma3zfc00dg99lfq3s0p163yv9-luajit-2.1.0-beta3/include
`

and this results into not passing any `-DCQUEUES_VERSION=foo` to compiler &ndash; it's just

`gcc -O2 -std=gnu99 -fPIC -g -Wall -Wextra  -Wno-missing-field-initializers  -Wno-override-init -Wno-unused  -DLUA_COMPAT_APIINTCASTS -I/nix/store/zrarsvfma3zfc00dg99lfq3s0p163yv9-luajit-2.1.0-beta3/include -D_REENTRANT -D_THREAD_SAFE -D_GNU_SOURCE  -DCOMPAT53_PREFIX=cqueues    -c -o /build/cqueues-20171014/src/5.1/cqueues.o /build/cqueues-20171014/src/cqueues.c`

I'm not really good in debugging complex gnu make stuff.  Let me attach [a full log](https://github.com/wahern/cqueues/files/3106678/cqueues-debug.log)
 with added `--debug=a`.

**Comment by daurnimator** [comment]
What does running this give you? `./mk/changelog version`

**Comment by vcunat** [comment]
Oh, I see now.  Even with `--debug=a` make was silent about attempting to run the script, so I assumed it never got to that.  The problem is that the build environment is missing git (because useless dependency there), so `command -v` in combination with `set -e` kills the script.

**Comment by vcunat** [comment]
OK, what about https://github.com/wahern/cqueues/pull/217 ?
