### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by otgo** [wahern/cqueues#220]
Im trying to do a async process, this is my testing script:
```lua
local cqueues = require 'cqueues'
local proc_functions = cqueues.new()
local proc_check = cqueues.new()
local function proc1()
    while true do
        proc_functions:loop()
    end
end
local function proc2()
    while true do
        local inpt = io.stdin:read()
        proc_functions:wrap(function()
            print("HELLO")
        end)
        -- proc_functions:loop() -- if I uncomment this, it works
    end
end
proc_check:wrap(proc1)
proc_check:wrap(proc2)
proc_check:loop()
```
Problem here is, i want to check if there are new functions, and execute it in "proc1"

How do I do that?

**Comment by daurnimator** [comment]
> ```lua
> local inpt = io.stdin:read()
> ```

This is blocking. You'll need to wrap it in a cqueues-yielding read operation. The easiest way to do so is: 
```
local cs = require "cqueues.socket"
local stdin = cs.fdopen(0)
--- setup code here
    local inpt = stdin:read()
--- etc.
```

**Comment by otgo** [comment]
but in my code im not using stdin?
It is only an example

**Comment by otgo** [comment]
Example:
```
local cqueues = require 'cqueues'
local proc_functions = cqueues.new()
local proc_check = cqueues.new()
local function proc1()
    while true do
        proc_functions:loop()
    end
end
local function proc2()
    while true do
           https = require 'ssl.https'
           https.request("nnnn")
            print("HELLO")
        end)
        -- proc_functions:loop() -- if I uncomment this, it works
    end
end
proc_check:wrap(proc1)
proc_check:wrap(proc2)
proc_check:loop()
```

**Comment by daurnimator** [comment]
> https.request("nnnn")

That is also a blocking operation. See `lua-http` instead.

**Comment by otgo** [comment]
so, how could I do it with a ssl request?

**Comment by RyanSquared** [comment]
[lua-http](https://github.com/daurnimator/lua-http) is a library that integrates properly with cqueues and allows for it to perform operations without blocking up your client. You can change your example to, instead of using `require 'ssl.https'`, instead require `'http.request` as provided by the library I mentioned. Examples on how to use an HTTP client with that library should exist on that link.

In addition to that, you're not checking errors returned from the `proc_functions` loop, so you should wrap the loop function call in an `assert()` or use some other method to handle the error.

**Comment by otgo** [comment]
okaay :3 thanks for it, i will answer there to make my request sucessfully

**Comment by otgo** [comment]
i have been testing without any request and i cant make a loop in while :(
Can I make a repository to see and show me if something is bad?
If you have some time.

**Comment by otgo** [comment]
This is a flowchart:

![initialization](https://user-images.githubusercontent.com/17806096/59145742-c7721200-89ad-11e9-912d-c557b4b338f7.png)

**Comment by daurnimator** [comment]
Do you still have an open question here? I'm not sure I see a question any more...

**Comment by otgo** [comment]
ahmm...

**Comment by otgo** [comment]
I mean, i want to do something like that
