### ISSUE TITLE
Do you know an option to make sockets with callbacks?

### ISSUE THREAD

**Issue by otgo** [wahern/cqueues#222]

**Comment by daurnimator** [comment]
You would just make a new thread and do your callback from there:

```lua
cq:wrap(function()
    return mycallback(mysocket:read())
end)
```

**Comment by otgo** [comment]
I mean something like NodeJS:
ex:
c:send("text", callbackhere)

**Comment by daurnimator** [comment]
That is up to you to build on top of cqueues if you want it.
