### ISSUE TITLE
installing on debian 9 using luarocks 3.3 with lua 5.1 fails

### ISSUE THREAD

**Issue by babakyakhchali** [wahern/cqueues#235]
Hi
I'm trying to install http 0.3-0 which depends on cqueues but I'm getting these errors:

root@stage-opensips:/usr/src/cqueues# luarocks install http 0.3-0 CRYPTO_DIR=/usr/local/ssl OPENSSL_DIR=/usr/local/ssl
Warning: falling back to wget - install luasec to get native HTTPS support
Installing https://luarocks.org/http-0.3-0.src.rock
Missing dependencies for http 0.3-0:
   cqueues >= 20161214 (not installed)
   luaossl >= 20161208 (not installed)
   basexx >= 0.2.0 (not installed)
   lpeg (not installed)
   lpeg_patterns >= 0.5 (not installed)
   binaryheap >= 0.3 (not installed)
   fifo (not installed)

http 0.3-0 depends on lua >= 5.1 (5.1-1 provided by VM)
http 0.3-0 depends on compat53 >= 0.3 (0.7-1 installed)
http 0.3-0 depends on bit32 (5.3.0-1 installed)
http 0.3-0 depends on cqueues >= 20161214 (not installed)
Installing https://luarocks.org/cqueues-20190813.51-0.src.rock

cqueues 20190813.51-0 depends on lua 5.1 (5.1-1 provided by VM)
Warning: unmatched variable LUA_LIBDIR
env: ‘/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/luapath’: Permission denied
env: ‘/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/luapath’: Permission denied
env: ‘/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/luapath’: Permission denied
make: execvp: /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/vendor.os: Permission denied
env: ‘/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/vendor.cc’: Permission denied
make: execvp: /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/lib/../../mk/vendor.os: Permission denied
make: execvp: /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/changelog: Permission denied
cp /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/config.h.guess /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/config.h
cp /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/config.h /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/config.h
env: ‘/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/mk/luapath’: Permission denied
make: execvp: /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/../mk/changelog: Permission denied
make: execvp: /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/../mk/changelog: Permission denied
make: execvp: /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/../mk/changelog: Permission denied
mkdir -p /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/5.1
gcc -O2 -fPIC -DLUA_COMPAT_APIINTCASTS  -D_REENTRANT -D_THREAD_SAFE -D_GNU_SOURCE -I"/usr/local/ssl/include" -I"/usr/local/ssl/include" -DCOMPAT53_PREFIX=cqueues    -c -o /tmp/luarocksueues-20190813.51-0-6857913/cqueues-rel-20190813/src/5.1/cqueues.o /tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/cqueues.c
/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/cqueues.c:47:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
                 ^
compilation terminated.
/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/GNUmakefile:83: recipe for target '/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/5.1/cqueues failed
make: *** [/tmp/luarocks_cqueues-20190813.51-0-6857913/cqueues-rel-20190813/src/5.1/cqueues.o] Error 1

Error: Failed installing dependency: https://luarocks.org/cqueues-20190813.51-0.src.rock - Build error: Failed building.

I installed luarocks from source and it is working with other libraries like luasocket or cjson successfully

I'm using openssl built from source and located in /usr/local/ssl

[luarocks-config.txt](https://github.com/wahern/cqueues/files/4399169/luarocks-config.txt)

**Comment by cleoold** [comment]
Try installing the dev package liblua5.1-0-dev https://packages.debian.org/search?keywords=liblua5.1 ?

**Comment by daurnimator** [comment]
You need lua headers installed.
