### ISSUE TITLE
lua 5.3 build failed

### ISSUE THREAD

**Issue by Jackson-soft** [wahern/cqueues#238]
❯ make
enabling Lua 5.1
enabling Lua 5.3
cc -o /home/jacksoncy/code/cqueues/src/5.1/cqueues.so /home/jacksoncy/code/cqueues/src/5.1/cqueues.o /home/jacksoncy/code/cqueues/src/5.1/socket.o /home/jacksoncy/code/cqueues/src/5.1/errno.o /home/jacksoncy/code/cqueues/src/5.1/signal.o /home/jacksoncy/code/cqueues/src/5.1/thread.o /home/jacksoncy/code/cqueues/src/5.1/notify.o /home/jacksoncy/code/cqueues/src/5.1/dns.o /home/jacksoncy/code/cqueues/src/lib/libnonlua.a /home/jacksoncy/code/cqueues/src/5.1/compat53.o -shared  -L/usr/local/lib -L/usr/local/lib   -lssl -lcrypto -lpthread -ldl -lrt -lm
/usr/bin/ld: /home/jacksoncy/code/cqueues/src/5.1/socket.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: multiple definition of `cqueue__poll'; /home/jacksoncy/code/cqueues/src/5.1/cqueues.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: first defined here
/usr/bin/ld: /home/jacksoncy/code/cqueues/src/5.1/errno.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: multiple definition of `cqueue__poll'; /home/jacksoncy/code/cqueues/src/5.1/cqueues.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: first defined here
/usr/bin/ld: /home/jacksoncy/code/cqueues/src/5.1/signal.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: multiple definition of `cqueue__poll'; /home/jacksoncy/code/cqueues/src/5.1/cqueues.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: first defined here
/usr/bin/ld: /home/jacksoncy/code/cqueues/src/5.1/thread.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: multiple definition of `cqueue__poll'; /home/jacksoncy/code/cqueues/src/5.1/cqueues.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: first defined here
/usr/bin/ld: /home/jacksoncy/code/cqueues/src/5.1/notify.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: multiple definition of `cqueue__poll'; /home/jacksoncy/code/cqueues/src/5.1/cqueues.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: first defined here
/usr/bin/ld: /home/jacksoncy/code/cqueues/src/5.1/dns.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: multiple definition of `cqueue__poll'; /home/jacksoncy/code/cqueues/src/5.1/cqueues.o:/home/jacksoncy/code/cqueues/src/cqueues.h:141: first defined here
collect2: 错误：ld 返回 1
make: *** [/home/jacksoncy/code/cqueues/src/GNUmakefile:83：/home/jacksoncy/code/cqueues/src/5.1/cqueues.so] 错误 1

❯ lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

**Comment by daurnimator** [comment]
See #233
