### ISSUE TITLE
cqueues.lua:85 expected 1 arguments, got 5

### ISSUE THREAD

**Issue by cmouse** [wahern/cqueues#244]
Hi!

When using cqeues in Dovecot push notification lua driver, I get the following error:

doveadm(testuser): Error: lua: /home/cmouse/.luarocks/share/lua/5.3/cqueues.lua:85: expected 1 arguments, got 5

using following code

```.lua
function dovecot_lua_notify_begin_txn(user)
  return {user=user}
end

function dovecot_lua_notify_end_txn(ctx, success)
  local cqueues = require("cqueues")
  local socket = require("cqueues.socket")

  local con = socket.connect("dovecot.org", 80)

  local inner = cqueues.new()
  local outer = cqueues.new()

  inner:wrap(function()
  	con:write("GET / HTTP/1.0\n")
  	con:write("Host: dovecot.org:80\n\n")

  	for ln in con:lines() do
  		dovecot.i_debug("a line")
  	end
  end)

  outer:wrap(function()
  	assert(inner:loop())
  end)

  assert(outer:loop())
end

function dovecot_lua_notify_event_message_append(ctx, event)
  dovecot.i_info("message appended")
end

function dovecot_lua_notify_event_message_new(ctx, event)
  dovecot.i_info("message delivered")
end
```

Any ideas what to do with this? To reproduce locally, you need to compile dovecot manually as it requires a patch to change how Lua scripts are handled.

**Comment by daurnimator** [comment]
Can you confirm that your cqueues.lua line 85 is the same as https://github.com/wahern/cqueues/blob/b0c2bc5979f008a39300b01a0dc3e967c6257be9/src/cqueues.lua#L85 ?

**Comment by cmouse** [comment]
Yes, I can confirm this.

**Comment by cmouse** [comment]
Forgot to mention, this is with lua5.3

**Comment by daurnimator** [comment]
We debugged on IRC; the issue was that dovecot was saving away a `lua_State*` and using that instead of the one passed to its C functions. All usage of coroutines was broken.
