### ISSUE TITLE
Nesting controllers / parent discovery

### ISSUE THREAD

**Issue by Oozlum** [wahern/cqueues#245]
What I am trying to achieve is to load a user-defined script as a wrapped function, and for that script to be able to use queues itself transparently (i.e. without introducing additional framework into the script's environment):

```lua
-- main.lua
local cq = require'cqueues'
local ctrl = cq.new()

ctrl:wrap(loadfile('script.lua'))

-- call ctrl:step() in event loop
```

```lua
-- script.lua
local cq = require'cqueues'

controller:wrap(function()
  cq.sleep(2)
  print('Finished')
end)
```

The issue is what is `controller`?  The way I see it, the script either has be able to do something like:
```lua
cq.get_my_parent_controller():wrap(...)
```
or:
```lua
local my_ctrl = cq.new()
my_ctrl:wrap(...)
-- how do I ensure my_ctrl:step() is called as part of the event loop?
```

What is the correct (recommended) way to achieve this?

**Comment by daurnimator** [comment]
> What is the correct (recommended) way to achieve this?

`cqueues.running()`

However a better pattern is that your code snippets just look like linear code: if they need to create their own threads they can create their own cqueues controller.

**Comment by Oozlum** [comment]
Great, thank you.  Meta question: how did you add the 'question' label?  I tried to do it when I created this issue, but couldn't see an option?
