### ISSUE TITLE
cqueues fails install within a Docker image; states 5.2-1 version is provided, when 5.2 is required

### ISSUE THREAD

**Issue by solares** [wahern/cqueues#248]
```
#8 10.42 Error: Failed installing dependency: https://luarocks.org/cqueues-20200726.52-0.src.rock - Build error: Failed building.
#8 10.45 cqueues 20200726.52-0 depends on lua 5.2 (5.2-1 provided by VM)
```

Same problem if I try 5.3 or 5.4, or 5.4.3 

Using [https://hub.docker.com/r/nickblah/lua/](https://hub.docker.com/r/nickblah/lua/) for the base image. 

Here's a gist with the dockerfile and the output of the failing command:
https://gist.github.com/solares/0842edc34c301bc5ff3a87df07e7348c

I don't understand what the `-1` versions are.

**Comment by daurnimator** [comment]
> #8 11.96 /bin/sh: 1: m4: not found

You need to have `m4` installed.

**Comment by solares** [comment]
Thank you. I discovered this soon after posting. I guess that -1 was a red herring.
