### ISSUE TITLE
Create lua rock

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#3]
Would like to be able to install cqueues via luarocks.

**Comment by daurnimator** [comment]
I've uploaded some scm rockspecs here: http://rocks.moonscript.org/modules/daurnimator/cqueues
I had to use a weird hack with the version as discussed with @hishamhm to have different make targets per lua version

**Comment by daurnimator** [comment]
I've been maintaining these for a while now over at https://luarocks.org/modules/daurnimator/cqueues

Should possibly be mentioned on website/README?

**Comment by mathstuf** [comment]
Is it possible to have rocks which support 5.2 as well?

**Comment by mathstuf** [comment]
Ah, now I see what the .53 suffix is about. Nevermind; the website doesn't show deps for old releases.

**Comment by daurnimator** [comment]
> Nevermind; the website doesn't show deps for old releases.

correct :)
There is an issue open against the site for it: https://github.com/leafo/luarocks-site/issues/64
