### ISSUE TITLE
socket:flush documentation bug

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#36]
> socket:flush([mode][, timeout])
> Flushes output buffer. Mode is one of the “nlf” flags described in socket.connect. A nil mode
implies “n”, i.e. no buffering and effecting a full flush. An empty string mode resolves to the
configured output buffering mode

The `socket.connect` docs do not have this description, `socket:setmode()` does.
Furthermore, the concept of a 'full flush' or 'fully buffered' are never explained

**Comment by wahern** [comment]
Fixed, more or less.

**Comment by daurnimator** [comment]
:+1:
