### ISSUE TITLE
:wrap does not mark cqs fd readable

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#40]
On my computer, the following has `r` empty:
```lua
local cqueues = require "cqueues"
local select = require "socket".select

local cq = cqueues.new()
cq:wrap(function()
	print("WRAPPED")
end)

local fake_sock = { getfd = function() return cq:pollfd() end }
local r, w = select({fake_sock}, {}, 3)
print("Should have cq's pollfd:", unpack(r))
```

I expect that `:wrap` would make the cq ready for reading.

When Integrating with another event loop, this was resulting in a stall of cqueues.

**Comment by daurnimator** [comment]
This might be the fix:
```diff
diff --git a/src/cqueues.c b/src/cqueues.c
index 28ba5bc..b6ac9bc 100644
--- a/src/cqueues.c
+++ b/src/cqueues.c
@@ -1646,6 +1646,7 @@ static void thread_add(lua_State *L, struct cqueue *Q, struct callinfo *I, int i
        LIST_INSERT_HEAD(&Q->thread.pending, T, le);
        T->threads = &Q->thread.pending;
        Q->thread.count++;
+       kpoll_alert(&Q->kp);
 } /* thread_add() */
```

**Comment by wahern** [comment]
What about having :timeout() return 0 seconds if any coroutine is pending to run? Doing kpoll_alert every time a coroutine is added to the controller seems kind of heavy weight.

**Comment by daurnimator** [comment]
Indeed, that sounds like a less resource intensive fix :)

**Comment by daurnimator** [comment]
In that case, why do we need alert at all?

**Comment by wahern** [comment]
Looking at the code, that should be the current behavior.

```C
static int cqueue_timeout(lua_State *L) {
        struct cqueue *Q = cqueue_checkself(L, 1);

        if (!LIST_EMPTY(&Q->thread.pending)) {
                lua_pushnumber(L, 0.0);
```

**Comment by daurnimator** [comment]
ah. hrm. well that explains why the snippet above doesn't work. I'll have to try and condense down the original bug again.

**Comment by daurnimator** [comment]
Hmmm. so the issue is that 
  - cqueues returns a long timeout (or none, in the case of and empty cq)
  - another (non-cqueues event) happens, which calls `cq:wrap()`
  - the cqueue will not be resumed again until the timer is expired (which is minutes/hours away; or never), or the file descriptor has an event.

The above fix works, as it causes the fd to poll ready, and hence the timeout is 'cancelled'.
We could possible reduce the number of extra syscalls by checking if a cqueue is currently running.

**Comment by wahern** [comment]
On Tue, Jan 13, 2015 at 09:58:13AM -0800, daurnimator wrote:
> Hmmm. so the issue is that 
>   - cqueues returns a long timeout (or none, in the case of and empty cq)
>   - another (non-cqueues event) happens, which calls `cq:wrap()`
>   - the cqueue will not be resumed again until the timer is expired (which is minutes/hours away; or never), or the file descriptor has an event.
> 
> The above fix works, as it causes the fd to poll ready, and hence the
> timeout is 'cancelled'. We could possible reduce the number of extra
> syscalls by checking if a cqueue is currently running.

That sounds like the right fix. I'm writing a patch now and will commit it
later today.

**Comment by daurnimator** [comment]
> That sounds like the right fix. I'm writing a patch now and will commit it
> later today.

great :) I've got a patch queued up for prosody once this is in.

**Comment by wahern** [comment]
Patch committed with cf11254a2fd7ae2a05f8399a3af85787b25201c7. I also refactored things so signaling a condition variable benefits from the same optimization--avoid calling kpoll_alert if the controller is still running and we can rely on :timeout returning a 0-second timeout.

**Comment by daurnimator** [comment]
great :)
This seems fix the issue.
