### ISSUE TITLE
Lua 5.1 + coco patch supported?

### ISSUE THREAD

**Issue by anders** [wahern/cqueues#41]
The documentation says:

````
1.2.1 LuaJIT, Lua 5.2, Lua 5.3

cqueues principally targets Lua 5.2 and above. It’s not fully portable
to Lua 5.1 because cqueues relies on ephemeron tables to prevent
coroutine/controller reference cycles, and because Lua 5.1 does not
support yielding from metamethods and iterators. LuaJIT removes the
latter of these handicaps, and so cqueues targets LuaJIT secondarily.
````

Lua 5.1 with [Coco](http://coco.luajit.org/) (by the LuaJIT author himself) also removes the yield from metamethod/iterator handicap. Should the documentation mention this?

**Comment by daurnimator** [comment]
As cqueues is targetted at working whether lua is embedded, or extended, users probably don't have the power to modify their lua installation.

In any case, the are few places in cqueues that a yield is inside of an iterator 

  -  `socket:lines()`
  - `socket:accept()`

It could be useful as a footnote, but as it is only relevant to an old lua release, I'm not sure if it makes sense going forward...

**Comment by wahern** [comment]
On Wed, Jan 07, 2015 at 01:12:15AM -0800, Anders Bergh wrote:
> The documentation says:
> 
> ````
> 1.2.1 LuaJIT, Lua 5.2, Lua 5.3
> 
> cqueues principally targets Lua 5.2 and above. It???s not fully portable
> to Lua 5.1 because cqueues relies on ephemeron tables to prevent
> coroutine/controller reference cycles, and because Lua 5.1 does not
> support yielding from metamethods and iterators. LuaJIT removes the
> latter of these handicaps, and so cqueues targets LuaJIT secondarily.
> ````
> 
> Lua 5.1 with [Coco](http://coco.luajit.org/) (by the LuaJIT author himself) also removes the yield from metamethod/iterator handicap. Should the documentation mention this?

Lua 5.1 with Coco isn't technically Lua 5.1, it's a patched Lua 5.1. I'm
reticent to mention that it might work with a patched version of Lua. My
intention was to leave it implied that if a patched version can do the
things mentioned, it might work, but the burden is on the user to ensure
compatibility.

Even better IMO than Coco, which plays games with the C stack, is Rici
Lake's yieldable for loops patch:

	http://lua-users.org/wiki/YieldableForLoops

Mike Pall adopted this approach for LuaJIT 2.0 and dropped Coco.

cqueues might work with a Lua 5.1 patched with Rici's code. I haven't tried,
though.

I'm not actually sure if cqueues still yields from any metamethods. That
part I might need to remove.

**Comment by daurnimator** [comment]
btw, another 5.1 feature missing is __gc on tables. This particularly matters in dns.resolvers.lua

**Comment by wahern** [comment]
Closing for now because nothing concrete to resolve.
