### ISSUE TITLE
Only catch yields with special cqueues POLL value

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#59]
For some reason a user might want to yield an object to a host application. At the moment, if this object is a condition object, cqueues will wait on it instead.

cqueues should only do it's thing when the hidden/magic `_POLL` value is yielded.

**Comment by wahern** [comment]
On Mon, Apr 06, 2015 at 02:19:51AM -0700, daurnimator wrote:
> For some reason a user might want to yield an object to a host
> application. At the moment, if this object is a condition object, cqueues
> will wait on it instead.

If the coroutine is being resumed by the cqueues controller, how can the
host application see the object? If this a feature in a fork?

**Comment by wahern** [comment]
Now I understand, this is a feature request, not a bug report :)

**Comment by daurnimator** [comment]
> IIUC, with this feature calling coroutine.yield would yield through the controller. In effect, causing cqueue:step to yield. A side-effect would be that all application code would have to use cqueues.poll if they wanted to effect a poll, so that the controller knows whether to propagate the yield, or process the yielded values directly for polling and timeout.

Yes, that is correct :)

**Comment by daurnimator** [comment]
I was doing some work on this over on a branch: https://github.com/daurnimator/cqueues/tree/59-catch-special-only

**Comment by wahern** [comment]
The regression test crashes with Lua 5.1:

```
$ ./59-catch-special-only.lua -r5.1
enabling Lua 5.1
enabling Lua 5.2
enabling Lua 5.3
59-catch-special-only: ........................................................
59-catch-special-only: ............................................zsh: segmentation fault  ./59-catch-special-only.lua -r5.1
```

**Comment by wahern** [comment]
Broken by merge of 149-no-ephemeron-table.
