### ISSUE TITLE
Use SO_ENOHOST

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#62]
I was `:write`ing to a newly `.connect`'d socket. and you get `socket:flush: No such file or directory` (because I typo-ed the hostname)
However, I was wondering how best to make nice error messages
i.e. it should really throw something like `"unable to resolve x.com"`

‎@wahern‎ said:
> I thought I fixed that. i guess not. 
> There's already an `SO_ENOHOST`. It just needs to be set properly: need to keep track of the number of host names we've seen in either `struct dns_addrinfo` or in `struct socket` somewhere.
> Then, in `so_getaddr_()`, if we've seen 0 addresses when we get `ENOENT` from `dns_ai_nextent`, translate it to `SO_ENOHOST`.
> otherwise just return `ENOENT`, and `so_exec` will return the last error from the previous host we tried to contact.

**Comment by wahern** [comment]
So SO_ENOHOST was really meant for cases where a host name or address was needed for an operation but it was never provided: for example, calling socket:connect when creating the socket with socket.fdopen--there's no host address to pass to the connect() function.

Instead I've added DNS_ENONAME and DNS_EFAIL, which are synonymous with POSIX EAI_NONAME and EAI_EFAIL. dns_ai_nextent will return one of these when appropriate, and it will bubble up to the the application.

**Comment by daurnimator** [comment]
With 53a826b the error message is now:
`socket:flush: The name does not resolve for the supplied parameters`

**Comment by daurnimator** [comment]
> Instead I've added DNS_ENONAME and DNS_EFAIL, which are synonymous with POSIX EAI_NONAME and EAI_EFAIL. dns_ai_nextent will return one of these when appropriate, and it will bubble up to the application.

It's possibly work noting that they are synonymous, but not equivalent. i.e. you can't use `gai_strerror` on them.

**Comment by daurnimator** [comment]
> It's possibly work noting that they are synonymous, but not equivalent. i.e. you can't use gai_strerror on them.

(I checked this because I was wondering about internationalisation). Maybe `dns_strerror` should just remap to the `EAI_*` defines and use `gai_sterror` so that libc takes care of localisation for us?

**Comment by wahern** [comment]
They can't be the same value because the error values are specially encoded: they're all negative (so they can be returned via the same path as system errors), and each component's set of error codes are sequential and in a unique range.

Calling out to gai_strerror isn't a bad idea, but is it really worth it? Nothing else is localized, yet. There's a ton of other issues to close out. Plus, I was reading through OpenBSD's getaddrinfo implementation, and they have errors codes like EAI_NODATA, which is distinct from EAI_NONAME in that EAI_NONAME is only triggered (AFAICT) by an NXDOMAIN response. Down the road one might want to add more specific error codes that aren't standard, possibly necessitating ugly portability hacks.

**Comment by daurnimator** [comment]
> Calling out to gai_strerror isn't a bad idea, but is it really worth it? Nothing else is localized, yet.

Probably makes it easier for users to google error messages + it means we get to maintain less user visible strings :)

> There's a ton of other issues to close out.

Indeed, this issue is low priority :)



> Down the road one might want to add more specific error codes that aren't standard, possibly necessitating ugly portability hacks.

I wasn't suggesting you remove the `DNS_*` codes; just that for known error codes we translate and divert to `gai_sterror`

**Comment by wahern** [comment]
Closing for now. We can leave I18N for another day. There are too many open issues and too little time.
