### ISSUE TITLE
Support for POLLPRI

### ISSUE THREAD

**Issue by fabled** [wahern/cqueues#68]
If polling interrupt driven GPIO it needs to be done with POLLERR | POLLPRI. Would be nice if this is possible.

See: https://www.kernel.org/doc/Documentation/gpio/sysfs.txt

**Comment by daurnimator** [comment]
> If polling interrupt driven GPIO it needs to be done with POLLERR | POLLPRI. Would be nice if this is possible.
> 
> See: https://www.kernel.org/doc/Documentation/gpio/sysfs.txt

To clarify: it seems you need one of `POLLERR` **or** `POLLPRI`.

At least on linux, (see `epoll_ctl(2)`) `EPOLLERR` will always be used.

Therefore.... this should actually already work? Have you tested it?

Otherwise, support for `POLLPRI` is requested as part of https://github.com/wahern/cqueues/issues/11.

I guess `POLLPRI` should be a "p" in the event mask?

**Comment by daurnimator** [comment]
> Therefore.... this should actually already work? Have you tested it?

It doesn't work at the moment, as the files are always readable and writable, so there's no way to poll for just `POLLERR`.

**Comment by fabled** [comment]
I somehow missed #11 - I basically need POLLPRI. POLLERR cannot apparently be specified in poll, it is "revents" only type. The sysfs file seems to return error for POLLIN / POLLOUT, so POLLPRI is needed. And it makes sense - there's no additional data to read; instead out-of-band event has happened on the fd.

I renamed this accordingly. But keeping this open as this is a small subset of #11.

**Comment by wahern** [comment]
Any suggestions on how to write a regression test for POLLPRI that, at a minimum, works across most Linux systems? In particular uses a commonly available device that doesn't require root permissions.

**Comment by daurnimator** [comment]
> Any suggestions on how to write a regression test for POLLPRI that, at a minimum, works across most Linux systems? In particular uses a commonly available device that doesn't require root permissions

Just open any 'file' in sysfs and poll it before reading. e.g.: 
```lua
local cqueues = require"cqueues";
local fd=assert(io.open("/sys/bus/clockevents/devices/clockevent0/current_device", "rb"));
print(cqueues.poll({pollfd=3; events="p"}))
```

(found via http://stackoverflow.com/a/27784401/282536)

**Comment by wahern** [comment]
I just committed basic POLLPRI support based on daurnimator's patch. Let me know if it works for you.

**Comment by daurnimator** [comment]
Closing this issue, as the basic capability was added with 9e3236c401ffd65291c79867a504452ce0829908.
Use `p` in `events` to wait for `POLLPRI`

Will continue to track the rest of changes in #11.
