### ISSUE TITLE
Portability issues

### ISSUE THREAD

**Issue by fabled** [wahern/cqueues#69]
Building the latest git head on Alpine Linux (using musl c-library) is successful, but has the following issues:

1. LIST_MOVE conflicts the one in newer BSD sys/queue.h (than the one in glibc):

cqueues/src/lib/notify.c:159:0: warning: "LIST_MOVE" redefined
 #define LIST_MOVE(head, elm, le) do { \
 ^
In file included from cqueues/src/lib/notify.c:34:0:
/usr/include/sys/queue.h:214:0: note: this is the location of the previous definition
 #define LIST_MOVE(head1, head2) do {     \
 ^

The inline LIST_MOVE seems to do a different thing. The BSD LIST_MOVE move the whole list chain from one headnode to another. Your LIST_MOVE seems to remove and requeue a single list entry. Consider renaming it - e.g. LIST_REQUEUE or similar.

2. Several of the feature tests do not yield correct results and cannot be overrided:

./src/cqueues.h:#define HAVE_EVENTFD (__linux && (GLIBC_PREREQ(2, 9) || UCLIBC_PREREQ(0, 9, 33)))
./src/lib/kpoll.c:#define HAVE_EPOLL_CREATE1 (HAVE_EPOLL && __GLIBC_PREREQ(2, 9))
./src/lib/kpoll.c:#define HAVE_PIPE2 __GLIBC_PREREQ(2, 9)

musl supports all of the above. There is no simple preprocessor directive to detect this though. The proper way to do this is to have ./configure type script to test the availability of these features; otherwise it'd be broken when the feature is implemented and you'd need manually to track all possible c-libraries and their versions.

See also: http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_there_no_MUSL_macro_.3F
  
As minimum it'd be nice to have #ifndef around these HAVE_* so I can as temporary workaround add them to CFLAGS. But in long term, it'd be better to have simple configure script to test if these features are available.

**Comment by daurnimator** [comment]
> musl supports all of the above. There is no simple preprocessor directive to detect this though. The proper way to do this is to have ./configure type script to test the availability of these features; otherwise it'd be broken when the feature is implemented and you'd need manually to track all possible c-libraries and their versions.

@wahern and I talked about using an autoconf script a few days ago.

I objected that they're relatively incompatible with the way lua libraries are built today. e.g. luarocks doesn't like them (it only supports plain makefiles).

Perhaps we could instead test for versions known to be *missing* functionality (and then builds would break on unknown libcs without the required functionality)

**Comment by wahern** [comment]
I can't find LIST_MOVE anywhere in the musl code, either in my Alpine installation or in the Alpine Git repo I just cloned. In fact, AFAICT musl doesn't provide sys/queue.h at all. The BSD macro suffix to concatenate lists is _CONCAT (e.g. SLIST_CONCAT, TAILQ_CONCAT): https://svnweb.freebsd.org/base/release/10.1.0/sys/sys/queue.h?revision=274417&view=markup#l102

I don't mind changing it, of course, but I'm curious where your sys/queue.h came from. There are doubtless several other issues building against musl, though. But nothing too difficult--I ported Lua Unix to musl a couple of months and it was relatively easy. But musl intentionally doesn't define any feature or version macros which identifies itself, so either it has to be detect by exclusion (doesn't help with versions, though), or we need to use autoconf.

Regarding autoconf, it can always be fired off from the Makefile itself. Autoconf doesn't require automake or libtool.

**Comment by fabled** [comment]
Alpine's sys/queue.h is provided by bsd-compat-headers package which comes from:
  http://git.alpinelinux.org/cgit/aports/tree/main/libc-dev

The header copy originates from NetBSD and is located at:
  http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/sys/queue.h

**Comment by wahern** [comment]
I'm kinda surprised that it compiles and works with musl just with the LIST_MOVE fix. Cool.

**Comment by daurnimator** [comment]
@fabled working for you now?

**Comment by fabled** [comment]
Looks good. Thanks.
