### ISSUE TITLE
Calendar based events

### ISSUE THREAD

**Issue by fabled** [wahern/cqueues#70]
Would be really useful to have cron type calendar tied events. That is to have a function that takes calendar specifier and waits until it. E.g. "Wait until Thursday 9am" or "Any weekday 9pm". This is high level enough to be implemented fully in lua, but I'm wondering what kind of API would be best. If this could be included in cqueues. And how it needs to be implemented for possible wall time changes (e.g. due to NTP, DST changes, etc).

**Comment by AlissaSquared** [comment]
Could you not do this with a cqueues.sleep() based on an os.difftime() in relation to the time in seconds as of current versus time in seconds from the epoch to the date involved? This seems rather easily implementable. I might build an example and post it in a bit, if I don't end up falling asleep first.

**Comment by AlissaSquared** [comment]
Untested. Make sure to wrap in a cqueues object?
```lua
function waitUntilDate( year, month, day, hour, min, sec )
  cqueues.sleep( os.difftime( os.time(), os.time( {
    year = year,
    month = month,
    day = day,
    hour = hour,
    min = min,
    sec = sec
  } ) ) )
end
```

**Comment by AndrioCelos** [comment]
What I've done previously is to wait one hour and check the clock each hour.

**Comment by AlissaSquared** [comment]
I'd rather use a mechanism that's based off of one event. Wouldn't want `24 * 7 * 4` events just if it's waiting a month.

**Comment by fabled** [comment]
But additional logic is required for the "Monday-Friday at 9:15am". We'd need code to calculate the next matching weekday. I think DST is actually not the big issue -- if we just convert to UTC all timestamps, DST is take care of. But we do need to take care of if NTP is adjusting time (system clock drift; leap seconds). This means we need to recalculate the sleep time when wall time change/jump is detected. Not sure how to do this properly.

Hourly check not acceptable, as I need minimum of minute precision. And having event fire off every minute sounds not nice. But probably is what I'll do until something better is available.

**Comment by daurnimator** [comment]
cqueues itself isn't the right place for this.
You can implement it using [luatz](https://github.com/daurnimator/luatz) for timezone/daylight savings information, then (on Linux), use a timerfd with `TFD_NOTIFY_CLOCK_SET` to get alerted of time adjustments

**Comment by daurnimator** [comment]
> (on Linux), use a timerfd with TFD_NOTIFY_CLOCK_SET to get alerted of time adjustments

Apologies, they renamed the flag to `TFD_TIMER_CANCEL_ON_SET` before release.

**Comment by daurnimator** [comment]
> But additional logic is required for the "Monday-Friday at 9:15am". We'd need code to calculate the next matching weekday.

> You can implement it using luatz for timezone/daylight savings information, then (on Linux), use a timerfd with TFD_NOTIFY_CLOCK_SET to get alerted of time adjustments

I coded up an example of how you might do this ^^

This uses ljsyscall create the timerfd. You may want to expose the functionality as a normal C library.

```lua
local cqueues = require "cqueues"
local luatz = require "luatz"
local syscall = require "syscall"

local new_settimeofday_notifier do
	local methods = { events = "r" }
	local mt = { __index = methods }
	local enum = 3 -- should be "abstime,cancel_on_set"
	function methods:reset()
		-- reading from the timerfd will reset the status if it's gone off.
		-- EAGAIN if it hasn't gone off yet
		-- ECANCEL if it has gone off
		self._fd:read(syscall.t.buffer(8), 8)

		assert(self._fd:timerfd_settime(enum))
	end
	function methods:pollfd()
		return self._fd:getfd()
	end
	function methods:close()
		return self._fd:close()
	end
	function new_settimeofday_notifier()
		local fd = assert(syscall.timerfd_create("realtime", "cloexec,nonblock"))
		local self = setmetatable({
			_fd = fd;
		}, mt)
		return self
	end
end

-- Modifies `t` to be the next matching day of the week
-- does not normalise
-- e.g. `nextwday(t, 1)` will return the current time on the next Sunday.
local function nextwday(t, x)
    assert(x>=1 and x<=7)
    t.day=t.day+(7-t.wday)+x
    return t
end

local mytz = luatz.get_tz()
local r = new_settimeofday_notifier()
repeat
	local now = luatz.timetable.new_from_timestamp(mytz:localise())
	print("It is currently " .. tostring(now) .. " (localtime)")

	-- Find the next 9:15 am on a weekday
	local alarm_time = now:clone()
	alarm_time.hour = 9
	alarm_time.min = 15
	alarm_time.sec = 0
	if now > alarm_time then
		alarm_time.day = alarm_time.day + 1
		alarm_time:normalise() -- will fixup wday
	end
	-- If it's a saturday or sunday, skip forward to monday
    if alarm_time.wday == 7 or alarm_time.wday == 1 then
        nextwday(alarm_time, 2)
		alarm_time:normalise()
    end

	print("Setting alarm for " .. tostring(alarm_time) .. " (localtime)")
	-- Convert from local to utc
	local wake_up_timestamp = mytz:utctime(alarm_time:timestamp())
	local seconds_until_alarm = wake_up_timestamp - luatz.time()
	r:reset() -- re-arm the notifier
	local which = cqueues.poll(seconds_until_alarm, r)
until which ~= r
r:close()

print("It is currently " .. tostring(luatz.timetable.new_from_timestamp(mytz:localise())) .. " (localtime)")
```
