### ISSUE TITLE
`:starttls` bypasses buffering

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#73]
`:starttls` bypasses buffering, and hence can miss data.

This example simulates a protocol that does TLS upgrades (for real life examples, look at IMAP, XMPP).
Some unencrypted data is transferred, then `:starttls` is called by each side; then some encrypted data should be transferred

```lua
local cqueues = require "cqueues"
local cs = require "cqueues.socket"
local cc = require "cqueues.condition"

local cq = cqueues.new()
local ready = cc.new()
cs.setmode("nb", "nb")
cq:wrap(function()
	local srv = cs.listen{host="127.0.0.1"; port=4567};
	ready:signal()
	local clt = srv:accept()
	assert(clt:write("unsecure\n"))
	clt:starttls()
	assert(clt:write("secure\n"))
end)
cq:wrap(function()
	ready:wait()
	print("CONNECTING")
	local clt = cs.connect{host="127.0.0.1"; port=4567};
	assert(clt:read() == "unsecure")
	print("STARTINGTLS")
	assert(clt:starttls())
	assert(clt:read() == "secure")
end)
local ok, err, errno, thd = cq:loop()
if not ok then
	print(debug.traceback(thd, err))
end
```

It currently fails due to `:read` buffering up the TLS data:
```
CONNECTING
STARTINGTLS
delayed-starttls.lua:13: [127.0.0.1.44488]:starttls: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.3/cqueues/socket.lua:90: in function </usr/share/lua/5.3/cqueues/socket.lua:75>
	(...tail calls...)
	/usr/share/lua/5.3/cqueues/socket.lua:297: in method 'starttls'
	delayed-starttls.lua:13: in function <delayed-starttls.lua:8>
```

A similar thing could happen on the sending side if the output buffer was not flushed before calling `:starttls`

**Comment by daurnimator** [comment]
The custom BIO mentioned in https://github.com/wahern/cqueues/issues/52#issuecomment-112868854 will probably help out here.

**Comment by wahern** [comment]
Using a BIO won't fix this because the buffering and TLS are handled entirely separately. This is actually non-trivial to fix and still maintain the current semantics whereby applications don't have to wait for DNS resolution, :connect, or :starttls to complete before beginning I/O operations.

To fix this will require introducing a simple state machine which ensures predicate operations complete, just like what lib/socket.c uses to progress the state forward when I/O is attempted. There's a related issue where, e.g., an application writes a command and then attempt to read a response, but blocks forever because they used the wrong buffering mode and forgot flush. To fix this I want to add an autoflush mode (enabled by default), which attempts to flush any buffered data whenever a read is attempted.

I realize the TLS issue is a significant. Even if not technically a bug, it's definitely a QoS issue. But unlike some common TLS buffering bugs, at least we're not accidentally writing out sensitive data unencrypted.

I want to cut a stable release before making any more big changes. In the meantime I think the best bet is to simply add a reminder to the documentation.

**Comment by daurnimator** [comment]
> Using a BIO won't fix this because the buffering and TLS are handled entirely separately.

I was imagining you first feed the BIO from the read buffer; and *then* swap over to `read`.

The write case can be solved by implicitly flushing as `:starttls` is called.

**Comment by wahern** [comment]
I've started a new branch: https://github.com/wahern/cqueues/tree/73-starttls-buffering

In writing a regression test I realized that you're not even seeing an issue with buffering. The message "unknown protocol" usually happens (as it does here) when both peers are acting as clients. TLS is client/server, but both are sending a client hello and both are expecting a server response. The following test works just fine for me with the existing code. Note that the function genkey is provided by regress.lua.

```lua
#!/bin/sh
_=[[
	. "${0%%/*}/regress.sh"
	exec runlua "$0" "$@"
]]
require"regress".export".*"

local cqueues = require "cqueues"
local cs = require "cqueues.socket"
local cc = require "cqueues.condition"

local cq = cqueues.new()
local ready = cc.new()
cs.setmode("nb", "nb")
cq:wrap(function()
    local srv = cs.listen{host="127.0.0.1"; port=4567};
    ready:signal()
    local clt = srv:accept()
    local key, crt = genkey()
    local ctx = require"openssl.ssl.context".new("TLSv1", true)
    ctx:setCertificate(crt)
    ctx:setPrivateKey(key)
    assert(clt:write("unsecure\n"))
    clt:starttls(ctx)
    assert(clt:write("secure\n"))
end)
cq:wrap(function()
    ready:wait()
    print("CONNECTING")
    local clt = cs.connect{host="127.0.0.1"; port=4567};
    assert(clt:read() == "unsecure")
    print("STARTINGTLS")
    assert(clt:starttls())
    assert(clt:read() == "secure")
end)
local ok, err, errno, thd = cq:loop()
if not ok then
    print(debug.traceback(thd, err))
end
```

However, if we swapped the roles and made B the server, then it would hang.

The issue with implicit flush on starttls is that the semantics of starttls were originally, and still are to a large extent, that it simply puts the socket into a TLS state. You don't need to wait for :starttls to complete before attempting to do a read or write. Which means the implicit flush can't happen in the Lua wrapper, but inside the C code.

The current code in the branch simply purges anything in the input buffer when :starttls is first invoked. This will work for protocols like SMTP, POP, etc. I'm not sure there are any protocols where it wouldn't work, other than in the contrived regression test. Not sure if I'll add BIO and input buffer salvaging with this branch, or put it off a little bit.

**Comment by daurnimator** [comment]
Ah, indeed. I thought it was weird the result was an error instead of a hang.


> I'm not sure there are any protocols where it wouldn't work

One example I know of is XMPP Quickstart, see https://xmpp.org/extensions/xep-0305.html#tcp

> In the client-to-server half of the first exchange, the client assumes that the server supports the XMPP STARTTLS extension so it pipelines its initial stream header, the <starttls/> command, and the TLS ClientHello message.
> 
> Example 1. Client Initiation
> ```xml
<stream:stream
  from='juliet@im.example.com'
  to='im.example.com'
  version='1.0'
  xml:lang='en'
  xmlns='jabber:client'
  xmlns:stream='http://etherx.jabber.org/streams'>
<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
TLS ClientHello
  ```

There is unencrypted data in the same packet as the TLS ClientHello.

To implement this in cqueues, I would expect code like this to work:
  - `accept()` the client
  - `read(-2^10)`: read *upto* a good chunk size of data
  - pass it to an xml parser (e.g. expat)
  - `write` (but not flush) the server stream start header
  - after I see the `<starttls/>`, I'd halt XML parsing
  - need to `:unget` any trailing data
  - use `:starttls` to start the server side TLS flow
  - finally `:uncork` to send everything (up and including the `TLS ServerHello`)

**Comment by wahern** [comment]
I've merged the 73-starttls-buffering branch. Let me know if it works for you.

**Comment by daurnimator** [comment]
> I've merged the 73-starttls-buffering branch. Let me know if it works for you.

The test passes :)

**Comment by daurnimator** [comment]
might be good to have a regression test that performs the `:unget` too.

**Comment by daurnimator** [comment]
btw, this is a fun example: https://gist.github.com/daurnimator/60fc881c374b56cebd5f
