### ISSUE TITLE
SO_REUSEADDR defaults to 'on' for non-table form

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#76]
`so_opts` has the reuseaddr option defaulting to `1`, while if you use the table form (via `lso_checkopts`) it defaults to off.

https://github.com/wahern/cqueues/blob/8a50ff968091f9faa8f4305227c84a405bb280da/src/lib/socket.h#L176

(Thanks to @AlissaSquared for reporting the issue that lead to discovering this)

**Comment by wahern** [comment]
AFAICT the code only sets the option if it's non-nil. lso_checkopts -> lso_altfield -> lso_getfield.

https://github.com/wahern/cqueues/blob/8a50ff968091f9faa8f4305227c84a405bb280da/src/socket.c#L433

More importantly, in my tests reuseaddr is always set using either the list or table constructor. In fact, if this weren't so, then O_NONBLOCK wouldn't be set, either, which would be a much more obvious issue.

**Comment by daurnimator** [comment]
> AFAICT the code only sets the option if it's non-nil. lso_checkopts -> lso_altfield -> lso_getfield.
> 
> https://github.com/wahern/cqueues/blob/8a50ff968091f9faa8f4305227c84a405bb280da/src/socket.c#L433
> 
> More importantly, in my tests reuseaddr is always set using either the list or table constructor. In fact, if this weren't so, then O_NONBLOCK wouldn't be set, either, which would be a much more obvious issue.

The code path is this one: https://github.com/wahern/cqueues/blob/8a50ff968091f9faa8f4305227c84a405bb280da/src/socket.c#L818

==> the defaults are used; which means reuseaddr is "on". when for the table contructor it goes via `lso_getfield` which makes if "off".

**Comment by daurnimator** [comment]
hrm.... now I can't replicate.... maybe I was just seeing things.
