### ISSUE TITLE
ALPN disappears after a some iterations

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#87]
Ran into this tonight..... not sure how to explain, so here's a demonstration:
```lua
local cqueues = require "cqueues"
local cs = require "cqueues.socket"
local openssl_ctx = require "openssl.ssl.context"
local pkey = require "openssl.pkey"
local x509 = require "openssl.x509"

local client_ctx = openssl_ctx.new("TLSv1_2")
client_ctx:setAlpnProtos({"foo"})

-- Server context
local server_ctx = openssl_ctx.new("TLSv1_2", true)
server_ctx:setAlpnSelect(function(ssl, protos) -- luacheck: ignore 212
	print("ALPN SELECT", protos)
	for _, proto in ipairs(protos) do
		if proto == "foo" then return "foo" end
	end
	return nil
end)
local crt = x509.new()
local key = pkey.new()
crt:setPublicKey(key)
crt:sign(key)
assert(server_ctx:setPrivateKey(key))
assert(server_ctx:setCertificate(crt))

local cq = cqueues.new()
for i=1, 50 do
	local s, c = cs.pair()
	cq:wrap(function()
		assert(s:starttls(server_ctx, nil))
	end)
	cq:wrap(function()
		assert(c:starttls(client_ctx, nil))
		local ssl = c:checktls()
		print("ALPN", ssl:getAlpnSelected())
	end)
	assert(cq:step())
end
assert(cq:loop())
```
Output:
```
ALPN SELECT	table: 0x8bc790
ALPN SELECT	table: 0x929140
ALPN SELECT	table: 0xa21bd0
ALPN	foo
ALPN SELECT	table: 0x8aa1b0
ALPN	foo
ALPN SELECT	table: 0xca5900
ALPN	foo
ALPN SELECT	table: 0xd3f9b0
ALPN	foo
ALPN SELECT	table: 0xf277f0
ALPN	foo
ALPN SELECT	table: 0x1068730
ALPN	foo
ALPN SELECT	table: 0x11a9b60
ALPN	foo
ALPN SELECT	table: 0x12eaae0
ALPN	foo
ALPN SELECT	table: 0x142ba30
ALPN	foo
ALPN SELECT	table: 0x882bd0
ALPN	foo
ALPN SELECT	table: 0x16ace40
ALPN	foo
ALPN SELECT	table: 0x17ed3c0
ALPN	foo
ALPN SELECT	table: 0x84b530
ALPN	foo
ALPN SELECT	table: 0xcaad90
ALPN	foo
ALPN	foo
ALPN	foo
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
ALPN	nil
```

Not sure if this is a cqueues bug, or in luaossl.
But it doesn't occur if you remove the `assert(cq:step())` in the `for` loop.... so there's some sort of interplay here.

**Comment by daurnimator** [comment]
By placing extra `collectgarbage` calls around I realised that the issue is caused by something not being anchored and getting collected early.

Further investigation makes me think that it's because of the `ex` data not getting held onto correctly.
Possibly because `initall` in luaossl gets called more than once.

Moving the `ex_newstate` call inside the 'once' area seems to make this bug go away:

```diff
@@ -7089,17 +7090,18 @@ static void initall(lua_State *L) {
                 * already been configured.
                 */
                OPENSSL_config(NULL);
-       }
 
-       pthread_mutex_unlock(&mutex);
+               if ((error = compat_init()))
+                       auxL_error(L, error, "openssl.init");
 
-       if ((error = compat_init()))
-               auxL_error(L, error, "openssl.init");
+               if ((error = ex_init()))
+                       auxL_error(L, error, "openssl.init");
 
-       if ((error = ex_init()))
-               auxL_error(L, error, "openssl.init");
+               ex_newstate(L);
+       }
+
+       pthread_mutex_unlock(&mutex);
 
-       ex_newstate(L);
 
        addclass(L, BIGNUM_CLASS, bn_methods, bn_metatable);
        addclass(L, PKEY_CLASS, pk_methods, pk_metatable);
```

**Comment by wahern** [comment]
Is openssl being loaded from something other than require? That is, being loaded twice from the same Lua interpreter, bypassing the package.loaded cache?

ex_newstate should definitely check whether the ex_state has already initialized for the Lua state.

**Comment by wahern** [comment]
Nevermind, it can also happen simply by loading a submodule for the first time after attaching data to an OpenSSL object created from another submodule.

I've committed the fix to luaossl and added a regression test to cqueues. The fix had to go into ex_newstate, not initall. ex_newstate cannot be run only once per process because there may be more than one interpreter per process, and the exdata state is per interpreter. It's purpose is to invalidate any attached data that might point back to a Lua interpreter that has been destroyed. OpenSSL objects created from a Lua interpreter can persist beyond the lifetime of that interpreter. For example, if some application code acquires an SSL_CTX reference created from one Lua interpreter, and uses it from other C code or from Lua code in another interpreter. Of course, they shouldn't be attaching Lua-based callbacks in that case, but I didn't like the idea of bad Lua code being capable of creating invalid C pointers.

Thanks for catching this!

**Comment by daurnimator** [comment]
Thanks! Fixed in https://github.com/wahern/luaossl/commit/f73eccfc8e589e6cc670c488b78715ee40b6985d
